### ISSUE TITLE
Images in questions (.png & .jpg) are not showing

### ISSUE THREAD

**Issue by amh-boston** [vtos/moodle-mod_adaptivequiz#4] opened 2022-02-08 15:43 UTC
@amh-boston Hi Andrew,
I would suggest you create a new issue for that, as this is entirely unrelated to the current closed issue where we're commenting :)
Also, it would be a huge help if you attached some description of setting up such questions so I would easily reproduce it to see what's happening. Perhaps, we can merge the Andriy's @semteacher solution (if they don't mind :) ) after that to see if it works for the current plugin's version. Thank you!

_Originally posted by @vtos in https://github.com/vtos/moodle-mod_adaptivequiz/issues/3#issuecomment-1032333453_

I attach a set of questions which in an adaptive quiz does not display the images:
[questions-AS Mathematics Benchmark Assessments -export-20220208-1709.xml.zip](https://github.com/vtos/moodle-mod_adaptivequiz/files/8025340/questions-AS.Mathematics.Benchmark.Assessments.-export-20220208-1709.xml.zip)

**Comment by vtos** [comment] 2022-02-08 19:52
@amh-boston Hi Andrew,
thanks for creating an issue. I would still appreciate if you added here some more info about the issue - what type of question you're adding, what settings the question has, where basically you expect those images to appear, etc. This all details will help to track the issue down.

**Comment by vtos** [comment] 2022-07-23 15:40
No details provided to reproduce the issue and detect it's caused by the plugin specifically, closing.

**Closed by vtos** 2022-07-23 15:40 UTC
