### ISSUE TITLE
Error trying to complete attempt record

### ISSUE THREAD

**Issue by caiadogithub** [vtos/moodle-mod_adaptivequiz#1] opened 2022-01-31 19:05 UTC
Hi,

Moodle 3.11.4+
PostgreSQL 12
PHP 7.4
Ubuntu 20.04

When I try to start an attempt I got this error message:

![Firefox_Screenshot_2022-01-31T19-03-54 155Z](https://user-images.githubusercontent.com/23316275/151856342-06e7e262-3afd-45b6-a261-5d272a8ac333.png)

Ricardo

**Comment by vtos** [comment] 2022-02-01 09:29
Hi @caiadogithub,
Thanks for posting an issue! Can you please post particular quiz settings you're trying it with, so I could quickly reproduce it?

**Comment by amh-boston** [comment] 2022-02-01 11:09
I am getting the exact same error messages when setting up a simple adaptive quiz.  If I do a normal quiz all is fine...

**Comment by vtos** [comment] 2022-02-01 11:17
@amh-boston hi,
can you please post your settings for the adaptive quiz activity where you're getting this error as well? Thank you!

**Comment by amh-boston** [comment] 2022-02-01 11:24
Really straight forward, hope these will help - adaptive quiz settings:
<img width="822" alt="Screen Shot 2022-02-01 at 1 21 18 PM" src="https://user-images.githubusercontent.com/98814308/151959717-11611e7f-80a3-4f0c-972a-3425fc6c546a.png">
<img width="802" alt="Screen Shot 2022-02-01 at 1 22 03 PM" src="https://user-images.githubusercontent.com/98814308/151959817-d428c3de-6167-4e7b-b873-3d75c75f3f62.png">
<img width="814" alt="Screen Shot 2022-02-01 at 1 22 31 PM" src="https://user-images.githubusercontent.com/98814308/151959881-c1cad8d7-1399-4e40-9bf7-304568691e35.png">
<img width="805" alt="Screen Shot 2022-02-01 at 1 22 50 PM" src="https://user-images.githubusercontent.com/98814308/151959936-d2f64dd7-882a-44a4-bd8f-ec13b37338d0.png">
<img width="807" alt="Screen Shot 2022-02-01 at 1 23 25 PM" src="https://user-images.githubusercontent.com/98814308/151960029-eafaa97c-aa94-4137-9209-5cf6b2844484.png">
<img width="804" alt="Screen Shot 2022-02-01 at 1 23 42 PM" src="https://user-images.githubusercontent.com/98814308/151960077-474f99fe-3ab3-426c-a42a-988603c80583.png">

**Comment by amh-boston** [comment] 2022-02-01 15:42
Thank you so much for engaging with my issue.  
The tagging was done properly but, in a set of questions in  a level say adpq_2 not all questions were tagged.
Is it essential that ALL questions must be tagged?
Also, I exported all the questions to a different moodle site, set up a adative quiz there with those questions, and all was fine...
Could this imply that the site where it does not work we may have a plugin 'clash'?

**Comment by caiadogithub** [comment] 2022-02-01 15:51
@vtos 

My mistaske!

I was using "adpq-001", instead of "adpq_1".

Sorry!

I works now!

Ricardo

**Comment by amh-boston** [comment] 2022-02-01 15:56
Glad yours is now fine Ricardo!
My side I am using adpq_1, adpq_2 and adpq_3

Andrew

**Comment by vtos** [comment] 2022-02-01 16:09
Andrew, it's hard for me to make any conclusions at this point, as it's just several days since I'm the plugin maintainer officially and have released a new version :) I'm still learning how it works internally myself, but now I have this error reproduced and can play with it to provide a solid fix. BTW, did you have a previous version of the plugin when you're trying the new one? Did you update the plugin or install from scratch, I mean the Moodle instance where you caught the error? Thank you for the input!

**Comment by amh-boston** [comment] 2022-02-01 16:15
We uninstalled the old version and then did a full reinstall.
Let me just post the error message I received so you have the detail.
Thank you so much!!!
![Screen Shot 2022-02-01 at 6 15 15 PM](https://user-images.githubusercontent.com/98814308/152006437-b1d20689-7b2f-443d-8ec3-bf664973eabe.png)
e the detail.

**Comment by caiadogithub** [comment] 2022-02-01 16:25
@amh-boston Check your "adpq_..." syntax.

When I corrected mine the error message was gone.

**Comment by amh-boston** [comment] 2022-02-01 17:17
Hi,
I did that immediately when I saw your posting...my side the tags are inorder.

A

**Comment by amh-boston** [comment] 2022-02-02 08:01
Hi again,
After checking the tag 'notation' I started wondering about a possible plugin conflict that may be the cause of the issue. Tested the same quiz on a test site with an older version of our current theme and it worked. So suspicion is that the people that 'maintain' our theme may have included a new plugin then sent an update of our theme through.  Will let you know if we can ID the plugin that may be the culprit.

**Comment by vtos** [comment] 2022-02-02 08:52
@amh-boston Hi Andrew,

Thank you for digging into that, but I guess it has little to do with the theme you're using. The problem is that once this error occurred for a certain user, this user will catch it again and again for the same quiz, this is just due to how the plugin internally works currently. If you properly tag your questions and try it with another user after that, it should work for this new user. That's why (probably) it worked in your other Moodle setups.
In the next minor release of the plugin (expected soon) both sides of this error will be fixed - more strict questions pool validation before creating a quiz, and fixing those cases which already triggered that error and make it appear again and again.

**Comment by amh-boston** [comment] 2022-02-02 10:07
Hi again,  this morrning tried to run the quiz again with logging activated, the errors that showed are attached...maybe there is a clue hiddenn that I just haven't picked up...
![image](https://user-images.githubusercontent.com/98814308/152133563-4ad7e02b-e6f6-4a6a-ab8e-ef41608afc4c.png)

**Comment by vtos** [comment] 2022-02-02 12:29
> Hi again, this morrning tried to run the quiz again with logging activated, the errors that showed are attached...maybe there is a clue hiddenn that I just haven't picked up...

@amh-boston FYI I've put this into a new issue as this differs from what's discussed in the current issue.

**Comment by vtos** [comment] 2022-02-03 09:51
@amh-boston You're welcome to discuss the #3 :)

**Comment by vtos** [comment] 2022-02-04 18:18
Fixed in [2.0.1](https://github.com/vtos/moodle-mod_adaptivequiz/releases/tag/2.0.1) release, closing.

**Closed by vtos** 2022-02-04 18:18 UTC
Labels: bug
